### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by AhernShaia** [AhernShaia/Tech-Tonic#18]

**Comment by shiangogo** [comment]
- [x] 在new文章同時新增標籤
- [x] 文章瀏覽頁面顯示文章標籤
- [x] 各標籤show頁面
- [x] 用戶可以追蹤標籤
- [x] 主頁顯示用戶追蹤了哪些標籤
- [x] 可以編輯文章有哪些tags
- [x] 用戶可以退追標籤
- [x] 標籤頁面的文章分頁
- [x] 標籤頁面的文章排序

**Comment by shiangogo** [comment]
已完成
