### ISSUE TITLE
tag無法顯示中文

### ISSUE THREAD

**Issue by AhernShaia** [AhernShaia/Tech-Tonic#31]
Tag內的文字輸入中文，傳到後端變成 __ 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/111140575/235568969-b1db393f-31a1-4d1a-ad27-365a60d0e25d.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/111140575/235569191-2b7964c2-3f2d-42d6-abeb-d76d09aa8241.png">
@shiangogo

**Comment by shiangogo** [comment]
已修

**Comment by shiangogo** [comment]
已修
