### ISSUE TITLE
英文轉中文

### ISSUE THREAD

**Issue by shiangogo** [AhernShaia/Tech-Tonic#58]
包括
- [ ]  文章內頁
- [ ] 文章卡片上的日期
- [ ] 文章卡片上的文章狀態
- [ ] 個人設定頁面
- [ ] 標籤內頁

**Comment by linchen5913** [comment]
![截圖 2023-05-11 上午11 04 23](https://github.com/13thTechTonic/Tech-Tonic/assets/61831040/bc2a162b-29a9-480b-916c-80626741b91b)
Placeholder也要改

**Comment by linchen5913** [comment]
![截圖 2023-05-11 上午11 03 19](https://github.com/13thTechTonic/Tech-Tonic/assets/61831040/e61511ab-94fe-4204-a8a3-1794eb5afd24)
src: FB
